DELETE http://localhost:3003/api/blogs/63f5e2bb348ade5c0c67c8dc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2dnYXJpIiwiaWQiOiI2M2Y0YWJmOWNlMDAxNjZjNWI1N2NhNDkiLCJpYXQiOjE2NzcwNTg4NDJ9.7NHxFSq3EMSt1Wn-4fDq_-J9MbwiqHZmMirD0pdJ8nw